# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environtment:
      MAVEN_OPTS: -Xmx3200m
    
    steps:
    - checkout

    -restore_cache:
      keys:
      - v1-dependencies-{{ checksum "pom.xml" }}
      - v1-dependencies-

    - run: mvn install -DskipTests

    - run: mvn dependency:go-offline

    -save_cache:
      paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml"}}

    - run: mvn integration-test